// Generated by CoffeeScript 1.12.2
(function() {
  var DBSCAN_TEST, THREE, meshlab,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  meshlab = require('../templates/meshlab');

  THREE = meshlab.THREE;

  DBSCAN_TEST = (function(superClass) {
    extend(DBSCAN_TEST, superClass);

    function DBSCAN_TEST() {
      return DBSCAN_TEST.__super__.constructor.apply(this, arguments);
    }

    DBSCAN_TEST.prototype.init = function(renderer) {
      var loader;
      DBSCAN_TEST.__super__.init.call(this, renderer);
      loader = new meshlab.STLLoader();
      return loader.load('/Users/jane/Documents/models/mesh_simple.stl', (function(_this) {
        return function(geometry) {
          var material, mesh;
          material = new THREE.MeshPhongMaterial({
            color: 0xff5533,
            specular: 0x111111,
            shininess: 200
          });
          mesh = new THREE.Mesh(geometry, material);
          return _this.add(mesh);
        };
      })(this));
    };

    return DBSCAN_TEST;

  })(meshlab.View);

  if (typeof module !== "undefined" && module !== null) {
    module.exports = DBSCAN_TEST;
  }

}).call(this);

//# sourceMappingURL=dbscan-test.js.map
