// Generated by CoffeeScript 1.12.2
(function() {
  var Blueprint, Function, THREE;

  THREE = require('../third-party/three/build/three.js');

  Function = require('./blueprint/function.js');

  Blueprint = (function() {
    function Blueprint() {
      this.scene = new THREE.Scene();
      this.camera = new THREE.OrthographicCamera(-100, 100, 100, -100, 0.1, 100);
      this.clock = new THREE.Clock();
      this.objects = {};
      return this;
    }

    Blueprint.prototype.init = function(renderer) {
      var geometry, material, mesh;
      renderer.setClearColor(0x162b42);
      this.camera.position.z = 100;
      geometry = new THREE.PlaneGeometry(5, 5);
      material = new THREE.MeshBasicMaterial({
        color: 0xff0000,
        wireframe: true
      });
      mesh = new THREE.Mesh(geometry, material);
      this.scene.add(mesh);
      this.objects['cube'] = mesh;
    };

    Blueprint.prototype.onRender = function() {
      var dt;
      dt = this.clock.getDelta();
    };

    return Blueprint;

  })();

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Blueprint;
  }

}).call(this);
